Algoritmo "Calculo Professor"

Var

Professor: Caractere
Horasdia: inteiro
ganhohora: real
Resultado: real

Inicio

escreva("Insira o nome do professor: ")
leia(Professor)
escreva("Insira a hora trabalhada pelo profissional: ")
leia(Horasdia)
escreva("Insira o valor ganho por dia: ")
leia(ganhohora)
Resultado:=(horasdia*ganhohora)
escreval("")
escreval("O Professor ", Professor, " recebe R$ ", Resultado, " por dia!")

Fimalgoritmo