Algoritmo "Gasto_Combustivel"


Var

Combustivel: real
valortotal: real
valordesejado: real

Inicio

Combustivel <- 3.85
escreval("-----------------------------------------")
escreval("------Calculo de Combustível-------------")
escreval("-----------------------------------------")
Escreva("Digite o valor desejado: ")
leia(valordesejado)
valortotal:= (combustivel * valordesejado)
escreval("Você vai gastar ",valortotal, ", para abastecer ",valordesejado, " litros!")

Fimalgoritmo