Algoritmo "Mod"

Var
x, y, quoc, resto: inteiro


Inicio
escreva("Valor de X é: ")
leia(X)

escreva("Valor de Y é: ")
leia(y)

quoc  <- x div y
resto <- x mod y

escreval("=====================RESULTADO===========================")
escreval("O quociente da divisão do valores informador é: ", quoc)
escreval("O resto da divisão dos valores informados é: ", resto)
escreval("=========================================================")
Fimalgoritmo