Algoritmo "semnome"

Var

Produto: caractere
valorunitario: real
quantidade: inteiro
pagar: real

Inicio

Escreva("Escreva o nome do produto: ")
leia(Produto)
Escreva("Informe o Valor Unitário do produto: ")
leia(valorunitario)
escreva("Infome a Quantidade desejada: ")
leia(quantidade)
pagar:=(valorunitario*quantidade)
escreval("O total a pagar por ",quantidade, " unidades do produto ",Produto, " é de R$ ",pagar)


Fimalgoritmo