Algoritmo "semnome"

Var
Percurso:inteiro
Velocidade: inteiro
tempopercorrido: inteiro

Inicio

Escreva("Descreva a distancia a percorrer: ")
leia(percurso)
escreval("")
escreval("")
Escreva("Descreva a velocidade percorrida: ")
leia(Velocidade)
escreval("")
escreval("")
tempopercorrido:=(percurso * Velocidade)
Escreval("O tempo para percorrer o percurso é de: ",tempopercorrido, " minutos!")


Fimalgoritmo